# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.21.6
minecraft_version_range=>=1.21.6
yarn_mappings=1.21.6+build.1
loader_version=0.16.14

# Mod Properties
mod_id=zombifiedplayer
mod_name=ZombifiedPlayer
mod_version=1.2.3-Fabric-mc1.21.6
maven_group=net.petemc.zombifiedplayer
archives_base_name=ZombifiedPlayer

# Dependencies
fabric_version=0.127.1+1.21.6

# Misc Dependencies
java_version_range=>=21
cloth_config_version=19.0.147
modmenu_version=15.0.0-beta.3
jade_version=6674245
contagion_version=6692344
undeadnights_version=6688191
