# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.21
minecraft_version_range=>=1.21 <1.21.2-
yarn_mappings=1.21+build.1
loader_version=0.15.11

# Mod Properties
mod_id=zombifiedplayer
mod_name=ZombifiedPlayer
mod_version=1.2.3-Fabric-mc1.21
maven_group=net.petemc.zombifiedplayer
archives_base_name=ZombifiedPlayer

# Dependencies
fabric_version=0.100.8+1.21

# Misc Dependencies
java_version_range=>=21
cloth_config_version=15.0.127
modmenu_version=11.0.1
jade_version=5571122
contagion_version=6134993
undeadnights_version=6100388
