# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.1
minecraft_version_range=>=26.1
loader_version=0.18.6
loom_version=1.15-SNAPSHOT

# Mod Properties
mod_id=zombifiedplayer
mod_name=ZombifiedPlayer
mod_version=1.6.0-Fabric-mc26.1
maven_group=net.petemc.zombifiedplayer
archives_base_name=ZombifiedPlayer

# Dependencies
fabric_api_version=0.144.0+26.1

# Misc Dependencies
java_version_range=>=25
cloth_config_version=26.1.154
modmenu_version=18.0.0-alpha.8
jade_version=7815591

contagion_version=8549277
undeadnights_version=7858565

trinkets_version=4.0.0-alpha.8+26.1
#trinkets_continued_version=3.12.0-26.1
cardinal_components_version=8.0.0

#pneumono_core_version=37kFBGwl
pneumono_gravestones_version=AnqTAASX
universal_graves_version=7916427

hardcore_revival_version=8240884

# Switch: which gravestone mod is loaded during runClient
# Possible values: universal_graves | pneumono_gravestones
#active_graves_mod=universal_graves
